In [ ]:
import numpy as np
a = np.array([1,2,3,4])
a, a.dtype
#a.shape

(array([1, 2, 3, 4]), dtype('int64'))

In [ ]:
import numpy as np
a = np.array([[1,2,3,4],[4,4,6,9]])
a.ndim, a.shape

(2, (2, 4))

In [ ]:
import numpy as np
b = np.arange(9).reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# a= np.zeros((3,4))
# a
# b= np.ones((3,4))
# b
a=np.random.randint(0,10,(2,3))
a

array([[5, 5, 1],
       [9, 7, 3]])

In [ ]:
c=np.array([[3,4,5,6],[4,5,6,8]])

array([[3, 4, 5, 6],
       [4, 5, 6, 8]])

In [ ]:
d=np.array([[5,6,9,9],[3,7,5,9]])
d

array([[5, 6, 9, 9],
       [3, 7, 5, 9]])

In [ ]:
e=np.concatenate((c,d),axis=1)
e

array([[3, 4, 5, 6, 5, 6, 9, 9],
       [4, 5, 6, 8, 3, 7, 5, 9]])

In [ ]:
f=np.stack((c,d), axis=1)
f

array([[[3, 4, 5, 6],
        [5, 6, 9, 9]],

       [[4, 5, 6, 8],
        [3, 7, 5, 9]]])

In [ ]:
f=np.hstack((c,d))
f

array([[3, 4, 5, 6, 5, 6, 9, 9],
       [4, 5, 6, 8, 3, 7, 5, 9]])

In [ ]:
f=np.vstack((c,d))
f

array([[3, 4, 5, 6],
       [4, 5, 6, 8],
       [5, 6, 9, 9],
       [3, 7, 5, 9]])

In [ ]:
import numpy as np
# Create and display zero, one, and n-dimensional arrays
zero_dim_array = np.array(5)
one_dim_array = np.array([1, 2, 3])
n_dim_array = np.array([[1, 2], [3, 4]])
for arr in [zero_dim_array, one_dim_array, n_dim_array]:
 print(f"Array:\n{arr}\nDimension: {arr.ndim}\nData type: {arr.dtype}\n")


Array:
5
Dimension: 0
Data type: int64

Array:
[1 2 3]
Dimension: 1
Data type: int64

Array:
[[1 2]
 [3 4]]
Dimension: 2
Data type: int64



In [ ]:
import numpy as np
# Create arrays of different dimensions
array_0d = np.array(5)
array_1d = np.array([1, 2, 3, 4, 5])
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
# Print arrays with shapes
for i, arr in enumerate([array_0d, array_1d, array_2d, array_3d]):
 print(f"{i}D Array:\n{arr}\nShape: {arr.shape}\n")


0D Array:
5
Shape: ()

1D Array:
[1 2 3 4 5]
Shape: (5,)

2D Array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)



In [ ]:
import numpy as np
array = np.array([[1, 2, 3], [4, 5, 6]]) # Shape (2, 3)
reshaped_array = array.reshape(3, 2) # Reshape to (3, 2), keeping 6 elements
print("Original Shape:", array.shape, "\nReshaped Shape:", reshaped_array.shape)

Original Shape: (2, 3) 
Reshaped Shape: (3, 2)


In [ ]:
import numpy as np
a = np.arange(1, 10)
print(a)
x = range(1, 10)
print(x) # x is an iterator
print(list(x))
# further arange examples:
x = np.arange(10.4)
print(x)
x = np.arange(0.5, 10.4, 0.8)
print(x)

[1 2 3 4 5 6 7 8 9]
range(1, 10)
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 0.5  1.3  2.1  2.9  3.7  4.5  5.3  6.1  6.9  7.7  8.5  9.3 10.1]


In [ ]:
#Task-to-do:-
# 4.1) Problem 1
#1) empty array with 2*2
import numpy as np
array = np.empty((2,2 ))
print(array)

[[1. 1.]
 [1. 1.]]


In [ ]:
#2) one array with size 4*2
import numpy as np
b = np.arange(8).reshape(4,2)
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [ ]:
#3)
array = np.full((2,4), fill_value=1)
array

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
#4)
array= np.zeros_like((2,2))
array

array([], dtype=float64)

In [ ]:
#5)
array=np.ones_like(())
array

array([], dtype=float64)

In [ ]:
#6)
new_list = [1,2,3,4]
array= np.array((new_list))
array

array([1, 2, 3, 4])

In [ ]:
#4.1.1) problem 2
#1)
a = np.arange(10,49)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [ ]:
#2)
import numpy as np
b = np.arange(9).reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
#3)
a = np.eye(3,3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#4)
b=np.random.random(30), array.mean()
b

(array([0.60877118, 0.83136032, 0.99041885, 0.8907261 , 0.89413577,
        0.4145095 , 0.69205493, 0.14452534, 0.99350094, 0.25355731,
        0.28910833, 0.63673783, 0.10944939, 0.89331405, 0.71086234,
        0.98874555, 0.71664038, 0.84622643, 0.51608352, 0.99742928,
        0.10484045, 0.16338875, 0.61781534, 0.44713065, 0.8630475 ,
        0.13997735, 0.58953793, 0.26829402, 0.36692321, 0.66801349]),
 2.5)

In [ ]:
#5)
a= np.random.rand(10,10), np.max, np.min
a

(array([[0.00945799, 0.0704341 , 0.53610139, 0.47463699, 0.97827482,
         0.1246824 , 0.87064853, 0.76975386, 0.59471167, 0.60553306],
        [0.86261903, 0.34291091, 0.87989389, 0.24334223, 0.06379005,
         0.49944907, 0.98865387, 0.25956053, 0.97399041, 0.24920129],
        [0.66575381, 0.51257036, 0.20997151, 0.64586147, 0.46074393,
         0.68387081, 0.48212966, 0.42876647, 0.66467569, 0.14859788],
        [0.48417341, 0.52516317, 0.24858779, 0.39786125, 0.29458018,
         0.68228128, 0.09951512, 0.34495596, 0.73286761, 0.96387823],
        [0.3165439 , 0.07899566, 0.21136861, 0.9460433 , 0.48095716,
         0.73011677, 0.36133657, 0.01302792, 0.48333289, 0.61963099],
        [0.14524245, 0.75323996, 0.51294971, 0.55461381, 0.53865866,
         0.32017056, 0.48070086, 0.93191252, 0.31004489, 0.48878184],
        [0.34450563, 0.14676716, 0.40229511, 0.4507051 , 0.12358988,
         0.05982068, 0.3382459 , 0.2175599 , 0.6554136 , 0.93497732],
        [0.04300122, 0.4807

In [ ]:
#6)
b=np.zeros(10)
b[4]=1
b

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [ ]:
#7)
arr=[1,2,0,0,4,0]
arr.reverse()
print(arr)

[0, 4, 0, 0, 2, 1]


In [ ]:
#8)
import numpy as np

x = np.ones((5, 5))
print("1 on the border and 0 inside in the array")
x[1:-1, 1:-1] = 0

print(x)

1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
#9)
import numpy as np
x = np.ones((3, 3))

x = np.zeros((8, 8), dtype=int)
x[1::2, ::2] = 1
x[::2, 1::2] = 1

print(x)

[[0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1]]


In [ ]:
#problem-3
#1)
x= np.array([[1,2],[3,5]])
y=np.array([[5,6],[7,8]])
sum= np.add(x,y)
sum

array([[ 6,  8],
       [10, 13]])

In [ ]:
#2)
x= np.array([[1,2],[3,5]])
y=np.array([[5,6],[7,8]])
diff= np.subtract(x,y)
diff

array([[-4, -4],
       [-4, -3]])

In [ ]:
#3)
y=np.array([[5,6],[7,8]])
product= np.multiply(2,y)
product

array([[10, 12],
       [14, 16]])

In [ ]:
#4)
y=np.array([[5,6],[7,8]])
square= np.square(y)
square

array([[25, 36],
       [49, 64]])

In [ ]:
#5)
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

a=np.dot(v,w)
b= np.dot(x,v)
c=np.dot(x,y)
print(a)
print(b)
print(c)

219
[29 77]
[[19 22]
 [50 58]]


In [ ]:
#6)
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

e=np.concatenate((x,y),axis=1)
print(e)

f=np.concatenate((v,w),axis=0)
print(f)

[[1 2 5 6]
 [3 5 7 8]]
[ 9 10 11 12]


In [ ]:
#7)
x = np.array([[1,2],[3,5]])
v = np.array([9,10])
e=np.concatenate((x,v))
print(e)
#value error: all the input arrays must have same number of dimensions,
# but the array at index 0 has 2 dimension(s)
# and the array at index 1 has 1 dimension(s)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [ ]:
#problem-4
#1.1)
import numpy as np

A = np.array([[3,4],[7,8]])
a=np.linalg.inv(A)

product=np.dot(A,a)
print(product)

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [ ]:
#1.2)

import numpy as np
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

AB = np.dot(A,B)
BA = np.dot(B,A)

print ("AB:")
print(AB)

print("\nBA:")
print(BA)

print ("AB != BA")


AB:
[[23 13]
 [51 29]]

BA:
[[36 44]
 [13 16]]
AB != BA


In [ ]:
#1.3)
import numpy as np

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

ABt = np.transpose(np.dot(A,B))
BtAt = np.dot(np.transpose(B),np.transpose(A))

print(np.array_equal(ABt,BtAt))
print("\n(AB)^T: ")
print(ABt)
print("\nB^t*A^t:")
print(BtAt)


True

(AB)^T: 
[[23 51]
 [13 29]]

B^t*A^t:
[[23 51]
 [13 29]]


In [ ]:
#2)
import numpy as np

A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([-1, -3, 9])

A_inverse = np.linalg.inv(A)
X = np.dot(A_inverse, B)

print("Solution for X, Y, Z:")
print(X)


Solution for X, Y, Z:
[ 2.  1. -2.]


In [ ]:
#3)
import numpy as np

A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([-1, -3, 9])

A_inverse = np.linalg.inv(A)
X = np.dot(A_inverse, B)

print("Solution for X, Y, Z using np.linalg.inv:")
print(X)

# Explore more functions in np.linalg
print("\nAdditional functionalities in np.linalg:")
print(dir(np.linalg))


Solution for X, Y, Z using np.linalg.inv:
[ 2.  1. -2.]

Additional functionalities in np.linalg:
['LinAlgError', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_umath_linalg', 'cholesky', 'cond', 'det', 'eig', 'eigh', 'eigvals', 'eigvalsh', 'inv', 'linalg', 'lstsq', 'matrix_power', 'matrix_rank', 'multi_dot', 'norm', 'pinv', 'qr', 'slogdet', 'solve', 'svd', 'tensorinv', 'tensorsolve', 'test']


In [ ]:
# 4.2) Experiment: How fast is numpy
#1)a)
import time

list1 = [i for i in range(1_000_000)]
list2 = [i for i in range(1_000_000)]

start_time = time.time()

result = [x + y for x, y in zip(list1, list2)]

end_time = time.time()

time_taken = end_time - start_time
print(f"Time taken for element-wise addition: {time_taken:.5f} seconds")



Time taken for element-wise addition: 0.09811 seconds


In [ ]:
#1)b)
import numpy as np
import time

# Create two large numpy arrays of size 1,000,000
array1 = np.arange(1_000_000)
array2 = np.arange(1_000_000)

# Start the timer
start_time = time.time()

# Perform element-wise addition
result = array1 + array2

# End the timer
end_time = time.time()

# Measure and print the time taken
time_taken = end_time - start_time
print(f"Time taken for element-wise addition with numpy: {time_taken:.5f} seconds")


Time taken for element-wise addition with numpy: 0.00859 seconds


In [ ]:
#2)a)
import time
import random

def multiply_lists(list1, list2):
    result = []
    for i in range(len(list1)):
        result.append(list1[i] * list2[i])
    return result

# Generate two lists of size 1,000,000 with random integers
list1 = [random.randint(1, 100) for _ in range(1000000)]
list2 = [random.randint(1, 100) for _ in range(1000000)]

# Measure the time taken
start_time = time.time()
result = multiply_lists(list1, list2)
end_time = time.time()

print("Time taken:", end_time - start_time, "seconds")

Time taken: 0.17275166511535645 seconds


In [ ]:
#2)b)
import numpy as np
import time

def multiply_arrays(array1, array2):
    result = array1 * array2
    return result

# Generate two numpy arrays of size 1,000,000 with random integers
array1 = np.random.randint(1, 100, 1000000)
array2 = np.random.randint(1, 100, 1000000)

# Measure the time taken
start_time = time.time()
result = multiply_arrays(array1, array2)
end_time = time.time()

print("Time taken with NumPy:", end_time - start_time, "seconds")

Time taken with NumPy: 0.00808262825012207 seconds


In [ ]:
#3)a)
import time
import random

def dot_product(list1, list2):
    result = 0
    for i in range(len(list1)):
        result += list1[i] * list2[i]
    return result

# Generate two lists of size 1,000,000 with random integers
list1 = [random.randint(1, 100) for _ in range(1000000)]
list2 = [random.randint(1, 100) for _ in range(1000000)]

# Measure the time taken
start_time = time.time()
result = dot_product(list1, list2)
end_time = time.time()

print("Time taken:", end_time - start_time, "seconds")

Time taken: 0.13132047653198242 seconds


In [ ]:
#3)b)
import numpy as np
import time

def dot_product_numpy(array1, array2):
    result = np.dot(array1, array2)
    return result

# Generate two numpy arrays of size 1,000,000 with random integers
array1 = np.random.randint(1, 100, 1000000)
array2 = np.random.randint(1, 100, 1000000)

# Measure the time taken
start_time = time.time()
result = dot_product_numpy(array1, array2)
end_time = time.time()

print("Time taken with NumPy:", end_time - start_time, "seconds")

Time taken with NumPy: 0.0022706985473632812 seconds


In [ ]:
#4)a)
import numpy as np
import time

# Generate two random NumPy arrays of size 1000x1000
matrix1 = np.random.randint(1, 10, (1000, 1000))
matrix2 = np.random.randint(1, 10, (1000, 1000))

# Measure the time taken
start_time = time.time()
result = np.dot(matrix1, matrix2)
end_time = time.time()

print("Time taken with NumPy:", end_time - start_time, "seconds")

Time taken with NumPy: 1.4712812900543213 seconds


In [ ]:
#4)b)
import numpy as np
import time

# Generate two random NumPy arrays of size 1000x1000
matrix1 = np.random.randint(1, 10, (1000, 1000))
matrix2 = np.random.randint(1, 10, (1000, 1000))

# Measure the time taken
start_time = time.time()
result = np.dot(matrix1, matrix2)
end_time = time.time()

print("Time taken with NumPy:", end_time - start_time, "seconds")

Time taken with NumPy: 2.667602777481079 seconds
